{% set version = "2.0.8" %}

package:
  name: bob.io.base
  version: {{ version }}

source:
  fn: bob.io.base-{{ version }}.zip
  url: https://pypi.python.org/packages/source/b/bob.io.base/bob.io.base-{{ version }}.zip
  md5: f81e1e04466048cb022f4fa363bf6fe0

build:
  number: 4
  skip: true  # [win]

requirements:
  build:
  - python
  - setuptools
  - bob.extension
  - bob.blitz
  - bob.core
  - hdf5 1.8.17|1.8.17.*
  - cmake
  - pkg-config
  - boost 1.61.*

  run:
  - python
  - bob.extension
  - bob.blitz
  - bob.core
  - hdf5 1.8.17|1.8.17.*
  - boost 1.61.*

test:
  imports:
  - bob
  - bob.io
  - bob.io.base

  commands:
    - nosetests -sv bob.io.base

  requires:
    - nose

about:
  home: http://github.com/bioidiap/bob.io.base
  license: Modified BSD License (3-clause)
  summary: Basic IO for Bob

extra:
  recipe-maintainers:
  - 183amir
